import os


SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_DATABASE_URI"]
WTF_CSRF_ENABLED = True
TALISMAN_ENABLED = False
ROW_LIMIT = 50_000
SUPERSET_WEBSERVER_PORT = 8088
FEATURE_FLAGS = {"ENABLE_TEMPLATE_PROCESSING": True}
